### ISSUE TITLE
'Public access is not permitted on this storage account' when i tried to download the data

### ISSUE THREAD

**Issue by wangskyGit** [microsoft/SimXNS#10]
Datasets and ckpts are not accessible now!!!

**Comment by lx865712528** [comment]
Thanks for the question! Fixed now. Please refer to [HOW_TO_DOWNLOAD](https://github.com/microsoft/SimXNS/tree/main/HOW_TO_DOWNLOAD.md).

**Comment by lx865712528** [comment]
If you want to use MASTER, we have also uploaded the pretrained MASTER checkpoints for [MARCO](https://huggingface.co/lx865712528/master-base-pretrained-msmarco) and [Wikipedia](https://huggingface.co/lx865712528/master-base-pretrained-wiki) to huggingface model hub.
