### ISSUE TITLE
How can I get the "passage_embedding.pb" and "passage_embedding2id.pb" ?

### ISSUE THREAD

**Issue by suiyize** [microsoft/SimXNS#11]
![image](https://github.com/microsoft/SimXNS/assets/71477998/16d41da0-a141-4919-ab37-35e97e4262e6)
In project **ALLIES**，How can I get the "**_passage_embedding.pb_**" and "**_passage_embedding2id.pb_**" ?

In BLOB, I did not see the relevant resources, if I need to embeding by myself, in the source code I did not see the relevant part of the content?

Looking forward to your reply !

**Comment by sunhaonlp** [comment]
Thank you for your interest in our project!

We have made the embedding files available at [GitHub - Microsoft/SimXNS: ALLIES - Released Resources](https://github.com/microsoft/SimXNS/tree/main/ALLIES#released-resources). If you're looking to evaluate ALLIES using different datasets, kindly refer to the instructions provided in our GitHub repository: [GitHub - Microsoft/SimXNS: ALLIES - Embedding Generation Notebook](https://github.com/microsoft/SimXNS/blob/main/ALLIES/embedding_generation.ipynb).

Best regards,
