### ISSUE TITLE
'ckpt/MS-Doc/adore-star'. If you were trying to load it from 'https://huggingface.co/models'

### ISSUE THREAD

**Issue by KhambardeCal** [microsoft/SimXNS#3]
OSError: Can't load the configuration of 'ckpt/MS-Doc/adore-star'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'ckpt/MS-Doc/adore-star' is the correct path to a directory containing a config.json file
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 18826) of binary: /home/socialab/miniconda3/envs/IR_SimANS-env/bin/python

**Comment by lx865712528** [comment]
Seems you didn't have the checkpoint settled in the corrent path.
