### ISSUE TITLE
 FileNotFoundError: [Errno 2] No such file or directory: '/home/socialab/Desktop/Kailash/SimXNS-main/SimANS/output/co_training_tq_SimANS_test/log.txt'

### ISSUE THREAD

**Issue by KhambardeCal** [microsoft/SimXNS#4]
FileNotFoundError: [Errno 2] No such file or directory: '/home/socialab/Desktop/Kailash/SimXNS-main/SimANS/output/co_training_tq_SimANS_test/log.txt'

**Comment by lx865712528** [comment]
Maybe the path or the file didn't exist. You can just creat one. BTW, which file you are running? You can provide more information for us to improve.

**Comment by Victoriaheiheihei** [comment]
hello,can you load the cpkt files successfully?  It shows "_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified." even though  I've already set the torch version to 1.7.1.

**Comment by Lancelot39** [comment]
A possible reason is that you have not create the folder under the path "/home/socialab/Desktop/Kailash/SimXNS-main/SimANS/output/co_training_tq_SimANS_test/". You can just try to create it, and rerun your code. Then, the code would also new the file log.txt, and automatically load the ckpt.

> hello,can you load the cpkt files successfully? It shows "_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified." even though I've already set the torch version to 1.7.1.

**Comment by Victoriaheiheihei** [comment]
> 
thank you！
