### ISSUE TITLE
Problem with Downloading Checkpoints

### ISSUE THREAD

**Issue by KhambardeCal** [microsoft/SimXNS#5]
I am writing to inform you that I have been facing an issue with downloading the checkpoints for the past 4 days. The download stops when it reaches 6-7 GB in size, and I am not sure if others are facing the same problem.

Could you please look into this and let me know if there is a solution or if anyone else is encountering a similar issue?

**Comment by lx865712528** [comment]
Hi! In the recent update, we refine the resources of [SimANS](https://github.com/microsoft/SimXNS/tree/main/SimANS) by uploading files in a seperated style and offering the [file list](https://github.com/microsoft/SimXNS/tree/main/SimANS#-how-to-use). Now you can download only the part you need. Enjoy.
