### ISSUE TITLE
Is SimANS do sampling with replacement?

### ISSUE THREAD

**Issue by awdrgyjilplij** [microsoft/SimXNS#7]
According to the code
random.choices(neg_candidates, weights=neg_scores, k=num_hard_negatives)

If it's true, why it is better than without replacement?

**Comment by awdrgyjilplij** [comment]
Also, s(q, d)=hq·hd can be tens, and many neg_scores=math.exp(-(neg_score - pos_score) ** 2 * self.tau) might be zero in python3

**Comment by lx865712528** [comment]
Our method is already sampling without replacement (无放回抽样).
Please refer to [https://github.com/microsoft/SimXNS/blob/main/SimANS/utils/MARCO_until_Doc.py#L127-#L148](https://github.com/microsoft/SimXNS/blob/main/SimANS/utils/MARCO_until_Doc.py#L127-#L148) as an example. Thanks!

**Comment by lx865712528** [comment]
> Also, s(q, d)=hq·hd can be tens, and many neg_scores=math.exp(-(neg_score - pos_score) ** 2 * self.tau) might be zero in python3

There are several ways to keep the exp computation more stable. Again in [https://github.com/microsoft/SimXNS/blob/main/SimANS/utils/MARCO_until_Doc.py#L127-#L148](https://github.com/microsoft/SimXNS/blob/main/SimANS/utils/MARCO_until_Doc.py#L127-#L148), we offer `self.b` as a bias term to keep it stable.
