### ISSUE TITLE
Problem with MASTER checkpoints

### ISSUE THREAD

**Issue by Victoriaheiheihei** [microsoft/SimXNS#8]
Hello,this is a really impressive work.
I've got some problems with the checkpoint. 
![image](https://user-images.githubusercontent.com/55309968/227133877-7fb0a2ee-1a85-4258-ab24-829aabd4a119.png)

you said that you initialized the model with bert, and I'm confused about which two layers you used to initialized the other heads,like c_head,query_head

**Comment by lx865712528** [comment]
We now provide the pretrained checkpoints using MSMARCO corpus and Wikipedia in huggingface.
- https://huggingface.co/lx865712528/master-base-pretrained-msmarco
- https://huggingface.co/lx865712528/master-base-pretrained-wiki
